### PR TITLE
passing all available resolvers to scalafmt

### PR DESCRIPTION
**Pull request by slivkamiro**
after a little digging I found another resolvers :) hope this helps with https://github.com/scalameta/scalafmt/issues/1521

### CODE REVIEW

**Comment by poslegm** [comment]
Thank you! Let's try it

**Comment by ceedubs** [comment]
Thank you @slivkamiro! I see a 2.3.2 tag on the release page, but I don't see an artifact in Maven Central yet. I'm happy to test this out in our CI environment once this is published.

**Comment by poslegm** [comment]
There is a lag (several hours) before artifact becomes available at Maven Central :(

**Comment by poslegm** [comment]
@ceedubs I was able to download the artifact now. Try it please

**Comment by ceedubs** [comment]
I just gave it a try. It looks like it's now failing because it isn't picking up the credentials associated with that resolver.

**Pull request merged**
