### PR TITLE
sbt cache usage for incremental formatting

### PR DESCRIPTION
**Pull request by poslegm**
I noticed that sbt plugin try to format not changed after previous compilation files. Because of this it is impossible to turn on `scalafmtOnCompile` in large projects. 

This PR is a try to use sbt cache to format only sources which will be compiled incrementally. I am not completely sure of the correctness of my implementation, but on my projects it does not format unchanged files (as a result, works faster).

Probably it will help with #9

### CODE REVIEW

**Comment by olafurpg** [comment]
Thank you for this contribution! Is someone able to review this PR? I personally don't use sbt-scalafix so I'm not the best to judge.

**Comment by olafurpg** [comment]
I asked for help on Gitter.

**Comment by olafurpg** [comment]
I agree, but currently I don't think the sbt plugin works with the latest scalafmt since the scalafmt-big module has been removed in favor of scalafmt-dynamic. It requires some work to update and I'm afraid I have limited time to work on scalafmt these days :(

**Comment by olafurpg** [comment]
the scalafmt-big module was removed because it was breaking our release process, publishing fatjars to maven is kinda flaky.

**Comment by dwijnand** [comment]
Why introduce a new key `scalafmtIncremental` instead of just redefining the `scalafmt` key to use caching?  My interest is because this solution works for `scalafmtDoFormatOnCompile`, but not for `scalafmtCheck`/`scalafmtSbtCheck`/`scalafmtCheckAll`.

**Comment by poslegm** [comment]
@dwijnand IMHO formatting only cached files is not very intuitive operation because user doesn't know which files will be formatted. So I prefer transparent and expected behaviour for _default_ commands.

And as user I don't want to consider sbt cache state when performing `scalafmt`/`scalafmtCheck` commands. What do you think about `*Incremental` suffix for other commands?

**Comment by dwijnand** [comment]
> What do you think about `*Incremental` suffix for other commands?

I think that's making the problem worse.

> So I prefer transparent and expected behaviour for _default_ commands.

The expected behaviour is all files are formatted by the end.  The fact that the task is aware that a file hasn't changed and therefore it skips formatting it is an optimisation detail that doesn't affect that user.

**Comment by poslegm** [comment]
@dwijnand  :thinking: ok, it sounds reasonable. I can send PR in the next couple of days.

**Comment by poslegm** [comment]
@dwijnand 

Currently I am working at requested changes. You requested caching for `scalafmtSbtCheck` command. But I did not found a way to fetch sbt cache for `*.sbt` and `project/*.scala` files.

Currently I works with sbt cache this way:

```scala
private def cached[T](cacheBaseDirectory: File, inStyle: FileInfo.Style)(
      action: Set[File] => T
  ): Set[File] => Option[T] = {
    import Path._
    lazy val inCache = Difference.inputs(
      CacheStoreFactory(cacheBaseDirectory).make("in-cache"),
      inStyle
    )
    inputs => {
      inCache(inputs) { inReport =>
        if (!inReport.modified.isEmpty) Some(action(inReport.modified)) else None
      }
    }
  }

cached(streams.value.cacheDirectory, ...)
```

It seems not working for `scalafmtSbtCheck`. Maybe you know how to fetch only changed `project/*.scala` and `*.sbt` files?

**Comment by dwijnand** [comment]
I've not worked with sbt's caching APIs, but I would try building something using https://github.com/sbt/util/blob/v1.2.4/util-tracking/src/main/scala/sbt/util/FileFunction.scala.

**Pull request merged**
