### PR TITLE
Incremental formatting by default

### PR DESCRIPTION
**Pull request by poslegm**
Based on discussion in #13 

1. Incremental formatting enabled by default for `scalafmt`, `scalafmtCheck` and `scalafmtAll` commands
2. Removed `scalafmtIncremental` task

Unfortunately, I could not find a way to detect changes in `.sbt` and `project/.scala` files. So those files will be formatted without cache usage. I think that it is not big problem because usually there are not very many such files.

### CODE REVIEW

**Comment by olafurpg** [comment]
Thank you for this contribution! Could someone help review this PR? Any thoughts  @tanishiking or @dwijnand?

**Comment by tanishiking** [comment]
Awesome! I'll check this later:smile:

**Comment by tanishiking** [comment]
@poslegm Can you rebase on master and resolve the conflicts?

**Comment by poslegm** [comment]
@tanishiking resolved

**Comment by tanishiking** [comment]
Thanks!

**Comment by dwijnand** [comment]
LGTM too.  The only thing is you cut a release with `scalafmtIncremental`, so you probably don't want to leave it undefined now.  I'd define that a breaking change.

**Comment by tanishiking** [comment]
Ah, that's right. Let's redefine a `scalafmtIncremental` as an alias of `scalafmt` task for avoiding a breaking change.

**Pull request merged**
